### ISSUE TITLE
Jar

### ISSUE THREAD

**Issue by j-truax** [stryker-mutator/sonar-stryker-plugin#3]
Does a JAR of the latest version of this plugin exist anywhere that I can download it?

Background: Trying to use this at the office but when we try to build the artifact, we get maven failures because our in house repository does not contain the this projects deps and/or the versions it requires. If an existing jar doesn't exist, this will require me to go through the paperwork to get all of these deps approved before we can start using sonar-stryker-plugin.

**Comment by simondel** [comment]
Thanks for notifying us! I created a release which you can find here: https://github.com/stryker-mutator/sonar-stryker-plugin/releases/tag/v0.0.1

Please let us know if the plugin works for you and if you have any feedback! I'll close this issue for now.

**Comment by j-truax** [comment]
@simondel Thank you very much! Will keep you updated :)
